### ISSUE TITLE
Some problem with the StanfordNLP

### ISSUE THREAD

**Issue by ji-xin** [shanzhenren/AFET#1]
After doing everything mentioned in README I tried `$ ./run.sh`, and got the following:
```
Step 1 Generate Features
Start nlp parsing
Traceback (most recent call last):
  File "DataProcessor/feature_generation.py", line 29, in <module>
    parse(raw_train_json, train_json)
  File "AFET/DataProcessor/nlp_parse.py", line 38, in parse
    parser = NLPParser('DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20')
  File "AFET/DataProcessor/nlp_parse.py", line 16, in __init__
    self.parser = StanfordCoreNLP(corenlp_dir)
  File "/usr/local/lib/python2.7/dist-packages/stanford_corenlp_python-3.3.10-py2.7.egg/corenlp/corenlp.py", line 348, in __init__
    self._spawn_corenlp()
  File "/usr/local/lib/python2.7/dist-packages/stanford_corenlp_python-3.3.10-py2.7.egg/corenlp/corenlp.py", line 337, in _spawn_corenlp
    self.corenlp.expect("\nNLP> ")
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f0a158ab0d0>
command: /usr/bin/java
args: ['/usr/bin/java', '-Xmx3g', '-cp', 'DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/joda-time.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/javax.json-api-1.0-sources.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/javax.json.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/stanford-corenlp-3.5.2-sources.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/jollyday.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/protobuf.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/stanford-corenlp-3.5.2-models.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/ejml-0.23.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/jollyday-0.4.7-sources.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/xom.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/xom-1.2.10-src.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/joda-time-2.1-sources.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/stanford-corenlp-3.5.2.jar:DataProcessor/stanford-corenlp-python/corenlp/stanford-corenlp-full-2015-04-20/stanford-corenlp-3.5.2-javadoc.jar', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-props', '/usr/local/lib/python2.7/dist-packages/stanford_corenlp_python-3.3.10-py2.7.egg/corenlp/default.properties']
buffer (last 100 chars): ''
before (last 100 chars): 's(ClassLoader.java:358)\r\n\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 9081
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 8192
ignorecase: False
searchwindowsize: 80
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("
NLP> ")
```

Seems to be the same problem with [https://github.com/dasmith/stanford-corenlp-python/issues/34](https://github.com/dasmith/stanford-corenlp-python/issues/34), i.e., the problem is not AFET's but StanforNLP's. Still I am wondering if you are getting the same problem and if yes, how do you solve it. Thanks!

**Comment by richardxiong** [comment]
Were you able to solve this problem? I encountered the same problem when I am trying to install the python interface [https://github.com/Wordseer/stanford-corenlp-python](url)

Please tell me if you have found a way to get through. Thanks!

**Comment by shanzhenren** [comment]
Hi @Ji-Xin @richardxiong, I tried on other machine environment (using the stanford-corenlp-full-2015-04-20 model) and it works for me (both for installing and for running the `python DataProcessor/feature_generation.py $Data` step). Could specify more details so then I can reproduce the errors?

**Comment by JohnnyLim** [comment]
I found that the file `default.properties` wasn't in my directory, and I added this file to the directory. Then the problem was solved.

**Comment by vinayneekhra** [comment]
I got the same issue. I was running it with Java 11 and with latest Stanford-corenlp package.
Running the tool with Java 8 and with recommended version of corenlp package solved the above issue for me.
